// Generated by genprov 2.0.24
#include "Employee_Provider.h"

CIMPLE_NAMESPACE_BEGIN

Employee_Provider::Employee_Provider()
{
}

Employee_Provider::~Employee_Provider()
{
}

Load_Status Employee_Provider::load()
{
    return LOAD_OK;
}

Unload_Status Employee_Provider::unload()
{
    return UNLOAD_OK;
}

Get_Instance_Status Employee_Provider::get_instance(
    const Employee* model,
    Employee*& instance)
{
    return GET_INSTANCE_UNSUPPORTED;
}

Enum_Instances_Status Employee_Provider::enum_instances(
    const Employee* model,
    Enum_Instances_Handler<Employee>* handler)
{
    return ENUM_INSTANCES_OK;
}

Create_Instance_Status Employee_Provider::create_instance(
    Employee* instance)
{
    return CREATE_INSTANCE_UNSUPPORTED;
}

Delete_Instance_Status Employee_Provider::delete_instance(
    const Employee* instance)
{
    return DELETE_INSTANCE_UNSUPPORTED;
}

Modify_Instance_Status Employee_Provider::modify_instance(
    const Employee* model,
    const Employee* instance)
{
    return MODIFY_INSTANCE_UNSUPPORTED;
}

/*@END@*/

CIMPLE_NAMESPACE_END
