//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2817]*/
static const Meta_Class* _meta_classes[] =
{
    &Employee::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_9923165039371FA697660D85C9253530;

/*[2844]*/
const Meta_Repository __meta_repository_9923165039371FA697660D85C9253530 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
