/*
 * This file is generated by script automatically. Please don't modify it manually.
 */

#include <stdlib.h>
#include <stdio.h>

#define MAX 5
#define MIN 7

typedef struct ABC
{
    int a;
};

typedef struct DEF
{
    float c;
};

char *GetName1(char *ptr)
{
    while (1) {
        int a = 2;
}} char *GetName2();
