#!/usr/bin/perl

package SrcFile;

sub new
{
    my $this = {};

    bless $this;

    return $this;
}

sub ApdInc
{
    my $this = shift;
    my ($file, $content) = @_;

    $this->{$file}{'include'} .= $content;
}

sub ApdMac
{
    my $this = shift;
    my ($file, $content) = @_;

    $this->{$file}{'macro'} .= $content;
}

sub ApdFun
{
    my $this = shift;
    my ($file, $content) = @_;

    $this->{$file}{'function'} .= $content;
}

sub ApdStr
{
    my $this = shift;
    my ($file, $content) = @_;

    $this->{$file}{'struct'} .= $content;
}

sub DESTROY 
{
    my $this = shift;
    my $file;
    my $content;

    my $header = "/*\n * This file is generated by script automatically. Please don't modify it manually.\n */\n\n";
    while (($file, $content) = each %$this) {
        open(OUTFILE, ">$file");
        print OUTFILE $header;
        print OUTFILE $content->{'include'}, "\n";
        print OUTFILE $content->{'macro'}, "\n";
        print OUTFILE $content->{'struct'}, "\n";
        print OUTFILE $content->{'function'}, "\n";
        close(OUTFILE);
        system("indent -br -i4 -nut -npsl -l80  -ce -bap -bad -bbo -npcs $file -o $file");
    }
}

1;
